### ISSUE TITLE
Possible to support plain ALSA?

### ISSUE THREAD

**Issue by RanzQ** [vovoid/vsxu#162]
If I understood correct, vsxu works only with PulseAudio. Would it be possible to make it work with ALSA, since I bet there are many people who wouldn't want to use pulseaudio. Or is this already supported if I make a custom build (I installed from PPA)?

**Comment by saidinesh5** [comment]
We use RtAudio, so  it builds with Alsa/Jack backends... Whatever is available at compile time...

https://github.com/vovoid/vsxu/blob/master/plugins/src/sound.rtaudio/CMakeLists.txt

**Comment by RanzQ** [comment]
Ok, thanks!

**Comment by RanzQ** [comment]
So, according to configuration, it should support ALSA now, but I don't have a clue how to select the audio source in player? I've setup a default recording device in my .asoundrc and it works for other applications.

```
configuring vsxu module            sound.rtaudio
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libpulse>=0.9.9'
--   found libpulse, version 4.0
-- checking for module 'libpulse-mainloop-glib'
--   found libpulse-mainloop-glib, version 4.0
-- Found PULSEAUDIO: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- checking for module 'jack'
--   found jack, version 0.122.0
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.27.2") 
```

Is it possible to select it somehow or does it automatically just select the "best" option?

**Comment by saidinesh5** [comment]
You can then send command line params like this to select the appropriate backend, if you have compiled the needed support for it.

https://github.com/vovoid/vsxu/blob/master/plugins/src/sound.rtaudio/main_sound.rtaudio.cpp#L131

**Comment by RanzQ** [comment]
Thank you, I will try this today.
