### ISSUE TITLE
Update the Addresses of fsf in these files

### ISSUE THREAD

**Issue by saidinesh5** [vovoid/vsxu#168]
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_sequence.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_font.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_param_sequence.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_widget_window.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_engine.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_quaternion_array.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_font_outline.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_texture_info.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_argvector.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_matrix.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_engine_abs.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_glsl.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/profiler/vsx_profiler_consumer.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_rand.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_mesh.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_mouse.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_string.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_comp_abs.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_glsl_es.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_param_sequence_list.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_vector_array.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vector/vsx_vector4.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_module_list_abs.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_bitmap.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/gl_helper.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_fifo.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vector/vsx_vector2.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_engine_helper.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_math.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_param_interpolation.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_widget_global_interpolation.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_command_client_server.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_command.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_quaternion.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_widget_time.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/container/vsx_avector.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_particlesystem.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/logo_intro.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_comp_channel.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsxg.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/container/vsx_array.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_module_list_factory.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_float_array.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/profiler/vsx_profiler.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/container/vsx_avector_nd.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsxfst.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_color.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_param.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_widget_camera.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/profiler/vsx_profiler_manager.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_comp.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_texture.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_param_abstraction.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_gl_es_shader_wrapper.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_grid_mesh.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_graphics/vsx_gl_global.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_module.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_sequence_pool.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_engine_helper_pool.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_bezier_calc.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vector/vsx_vector3.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_bspline.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine_audiovisual/vsx_manager.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/widget/vsx_widget.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_abstract.h
[  235s] vsxu-devel.x86_64: W: incorrect-fsf-address /usr/include/vsxu/engine/vsx_timer.h
[  235s] The Free Software Foundation address in this file seems to be outdated or
[  235s] misspelled.  Ask upstream to update the address, or if this is a license file,
[  235s] possibly the entire file with a new copy available from the FSF.

**Comment by jaw** [comment]
This is maintained in trello now
