### ISSUE TITLE
What version of cal3d is vsxu written for?

### ISSUE THREAD

**Issue by quequotion** [vovoid/vsxu#170]
I have cal3d 0.11.0-6 installed, which is missing a number of the files specified by vsxu's cmake scripts.

I have attempted to work around this by patching mesh.importers/CMakeLists.txt to remove non-existant file names, but then vsxu fails to build because:

    In file included from /build-dir/plugins/src/mesh.importers/main_mesh.importers.cpp:32:0:
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h: In member function ‘virtual void module_mesh_cal3d_import::param_set_notify(const vsx_string<>&)’:
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h:337:17: error: ‘TiXmlDocument’ was not declared in this scope
                     TiXmlDocument doc;
                 ^
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h:338:17: error: ‘doc’ was not declared in this scope
                     doc.Parse(a);
                     ^
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h:351:17: error: ‘TiXmlDocument’ was not declared in this scope
                     TiXmlDocument doc;
                     ^
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h:352:17: error: ‘doc’ was not declared in this scope
                     doc.Parse(a);
                     ^
    /build-dir/plugins/src/mesh.importers/module_mesh_cal3d_loader_threaded.h:394:41: error: ‘class CalCoreSubMorphTarget’ has no member named ‘name’
                 mi.name = morph_targets[i]->name().c_str();
                                             ^
    plugins/src/mesh.importers/CMakeFiles/mesh.importers.dir/build.make:62: recipe for target 'plugins/src/mesh.importers/CMakeFiles/mesh.importers.dir/main_mesh.importers.cpp.o' failed

Perhaps, if I knew what version of cal3d vsxu was looking for, I might be able to port it to the current one.

**Comment by quequotion** [comment]
This patch removes non-existent files, forces cmake to look where the files are installed (on ArchLinux) and forces cmake to look for header (.h) files. cmake does not seem capable of finding anything at all otherwise, and fails anyway.

[cal3d-workaround.txt](https://github.com/vovoid/vsxu/files/60484/cal3d-workaround.txt)

**Comment by jaw** [comment]
we have our own semi-maintained version of cal3d, did you do: git submodule update --init
after cloning vsxu?

**Comment by quequotion** [comment]
Nope! This also for the 0.6.0 branch?

**Comment by jaw** [comment]
Yep. 0.6.0 uses the submodule.

Master branch houses its own cal3d found here:

https://github.com/vovoid/vsxu/tree/master/plugins/src/mesh.importers/cal3d

If master branch tries to find your installed cal3d, then something is wrong in the CMake scripts.

(We have always needed to hack around in cal3d codebase for various reasons)
