### ISSUE TITLE
I have Stereo Mix as the default, also set to listen to this device, VSXu is still blank

### ISSUE THREAD

**Issue by irrelevantpelican** [vovoid/vsxu#172]
Here's a screen shot of my recording settings:  http://i.imgur.com/1ed7zOc.png

I already set stereo mix as default, but it seems to have no effect.

My computer is connected to a TV and I'm listening to the music through headphones connected to the TV, would that affect anything? 
![messed up](https://cloud.githubusercontent.com/assets/16588112/12163300/6f66b01c-b4da-11e5-88d6-00e3bc7380b2.png)

**Comment by jaw** [comment]
Do you see the VU meter moving in the screenshot when playing music?

Maybe you are playing on some other device than the default one?
(Sorry for late reply)

**Comment by DarkDot** [comment]
The Playback device also needs to be the same sound card as the recording device.

**Comment by lolmaus** [comment]
I don't understand how to achieve that.

I set the same device as the default on both tabs. On the Playback tab the meter is moving for the device, on the Recording tab it isn't. :( How do I make it move?

**Comment by DJPlaya** [comment]
Since 0.6.3, it is possible to select the Audio Input in the Launcher or using -audio_input_device ID

This Issue should be closed then

**Comment by quequotion** [comment]
What type of identification is expected for "ID"?

A number from alsa? A name from pulseaudio?
