### ISSUE TITLE
infinite loop for certain .vsx

### ISSUE THREAD

**Issue by andy-upsearch** [vovoid/vsxu#174]
Program becomes unresponsive when certain viz files are played. Win10 laptop with standard cheap Realtek audio. For example, "Flies by Asterix.vsx"

LOG: waiting for module: texture;loaders;png_cubemap_load with name: png_cubemap
_load

**Comment by lunarlabs** [comment]
Same problem here, using HP Beats Audio Realtek drivers.

**Comment by jaw** [comment]
Could it be that you are playing via some other sound card? I.e. bluetooth or USB headphones?
In order for Stereo Mix to work, you have to play on that very soundcard to which it is attached.
