### ISSUE TITLE
Win10 Error

### ISSUE THREAD

**Issue by Traderain** [vovoid/vsxu#176]
C:\Users\Traderai>"F:\Program Files\Vovoid VSXu 0.5.0\vsxu_player.exe"
INFO: app_init
INFO: app_init done
INFO: app_draw first
error in png loader when loading share\font/font-ascii.png: i_filesystem.fp not valid on line 134
INFO: app_draw first done
render first
font could not bind texture!

C:\Users\Traderai>

**Comment by jaw** [comment]
you should do cd "F:\Program Files\Vovoid VSXu 0.5.0"
first I think, it expects the current directory to be that.

**Comment by Traderain** [comment]
Thanks for the reply but it does not work either that way.

**Comment by jaw** [comment]
Ok, what GPU do you have?

**Comment by Traderain** [comment]
These are my specs:
![image](https://cloud.githubusercontent.com/assets/6411732/20305058/d9b2569c-ab33-11e6-9d83-9f92a36fd2cc.png)
And my graphics card is this:
![image](https://cloud.githubusercontent.com/assets/6411732/20305101/11e29888-ab34-11e6-8aa9-b17aab1965a2.png)
