### ISSUE TITLE
Compiling on raspberry pi

### ISSUE THREAD

**Issue by rambo** [vovoid/vsxu#177]
Made some quick-and-dirty changes to get it to compile (rpi3, different -march flag required for rpi1/2) but have not tested yet

https://gist.github.com/rambo/ff7b90535e5dcd5abfa9f2925cce864e

**Comment by jaw** [comment]
Sorry, this will never work as rpi uses OpenGL ES (1.0/2.0) and VSXu is written for regular OpenGL

**Comment by rambo** [comment]
ok, I assumed there was GLES port since I saw there was N900 port and this post:

"""This is targetted for the VSXu version after the upcoming 0.4. Basically the issue with the raspberrypi was adding the necessary changes in the cmakelists and it should work the same way it did on the N900. If gettiing to compile is all that you want, it isnt even that difficult."""

But maybe it got dropped. 

#89  is still open though, any plans ?

**Comment by jaw** [comment]
Not happening unless some volunteer wants to put in 500+ hours and then maintain that code.

Also, those mobile class GPUs probably are not powerful enough to run most visuals...

From a pure architecture standpoint - porting something to GL ES now that we have Vulkan is kind of stupid. Then it'd be better to rewrite portions of VSXu using Vulkan instead.
