### ISSUE TITLE
0.6.0 release lacks third party sources/submodules!

### ISSUE THREAD

**Issue by WoefulDerelict** [vovoid/vsxu#183]
The source tarball and release tags do not include the third party/submodule sources causing the build to fail as the files for cal3d, freetype and so on do not exist and it can't find them.

While attempting to build the latest release from source archive on Arch Linux the process explodes with the following:

CMake Error at lib/engine_graphics/CMakeLists.txt:184 (add_library):
  Cannot find source file: thirdparty/ftgl/src/FTBuffer.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at plugins/CMakeLists.txt:59 (add_library):
  Cannot find source file: /home/llewelyn/ArchPackageSources/vsxu/src/vsxu-0.6.0/plugins/src/mesh.importers/cal3d/cal3d/src/cal3d/animation_action.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  plugins/src/mesh.importers/CMakeLists.txt:93 (CREATE_MODULE)

CMake Error at lib/compression/CMakeLists.txt:146 (add_library):
  Cannot find source file: thirdparty/lzma-sdk/C/Alloc.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: vsx_engine_graphics
CMake Error: Cannot determine link language for target "vsx_engine_graphics".
CMake Error: CMake can not determine linker language for target: mesh.importers
CMake Error: Cannot determine link language for target "mesh.importers".
CMake Error: CMake can not determine linker language for target: vsx_compression
CMake Error: Cannot determine link language for target "vsx_compression".

None of the referenced files exist in the archive, rendering it unable to build a working copy of the software.

In order to successfully build vsxu 0.6.0 one found it necessary to clone the release tag and run git submodule update --init

**Comment by jaw** [comment]
Oh, bummer.

Do you have any preferred caused of action? 
I guess we could add a "full" tarball...

**Comment by WoefulDerelict** [comment]
A full tarball would make for a more robust distribution and make building and packaging this a great deal easier. Wandering off to fetch all the missing bits and adding them to the rest of the source from the current tarball is quite a chore and one found it easier to just grab the repo from GitHub and ignore the tarball altogether. I'm not incredibly uncomfortable with this but I suspect other users may prefer building from a complete archive instead of fussing with git.

One's local Arch Linux builds of the release tag and the master branch have built and ran quite well. One hasn't noticed any issues yet and presently none of the other users visiting the AUR and updating to 0.6.0 using the PKGBUILDS I maintain there have reported encountering any errors with the software.
