### ISSUE TITLE
No submodules in source taball

### ISSUE THREAD

**Issue by cwilling** [vovoid/vsxu#187]
The official tarball doesn't include any of the submodules that would be dragged in by running 'git submodule update --init' after a 'git clone ...'. Consequently, cannot build from the source tarball.

Could you make a new release that includes the submodules please?

**Comment by WoefulDerelict** [comment]
This was also an issue with the previous release [https://github.com/vovoid/vsxu/issues/183]. I'm not sure if the end user is expected to fetch those separately or it's just an oversight in how things are tagged and packaged for distribution in the tarball. It has lead to the AUR ignoring the tarball and just cloning the release from git as a build platform for Arch users.

**Comment by cwilling** [comment]
Ah, I should have noticed #183 - same problem. The proposed solution there of a "full" tarball is the one I'd endorse. As maintainer of vsxu package at slackbuilds.org, I can certainly generate a suitable tarball for end users myself but an official upstream tarball is always preferred.

**Comment by jaw** [comment]
Problem is github generates these tarballs automatically and I can't seem to find a way to replace them. Maybe you know a better solution? One option is of course to deliver tarballs via our homepage instead, or additionally supply manual tarballs so you'd end up with 4 tarballs per release. What do you think is best?

**Comment by cwilling** [comment]
Googling around, it seems this is a common problem with lots of requests over the years to Github to look into  & fix but no "built in" solution yet. It seems such an obvious thing to want to do, I just assumed it was possible but apparently not.
As to the place to host specially crafted tarballs containing the necessary submodules, it doesn't really matter although it seems neater to have them all (github generated + specially crafted) in the one place, if it's easy to arrange.

**Comment by WoefulDerelict** [comment]
One would need to check to be sure; however, I believe in order to include submodules in the GitHub tarball for a release those submodules need to be explicitly tagged so they're frozen at the time of release along with everything else. None of the submodules are included in the recent release tags so the dependency folder and all the third party submodules are missing from the automatically generated archive.

**Comment by cwilling** [comment]
Until a "full" tarball is available here, I've constructed one myself for users of slackbuilds.org (SBo) build scripts (rather than doing it in the  build script itself, like AUR). Its at: https://sourceforge.net/projects/slackbuildsdirectlinks/files/vsxu/vsxu-0.6.1.0.tar.gz and is distinguished from the tarballs here by adding a ".0" to the version field i.e. 0.6.1.0 at slackbuildsdirectlinks is the full version of 0.6.1 here.

I hope that's OK and doesn't step on any toes.

chris

**Comment by jaw** [comment]
AAAAH MY TOES!!!! no, it's fine :) and yes, I'm lazy. thanks.

**Comment by WoefulDerelict** [comment]
Following the lead of build scripts for Arch Linux repo packages like networkmanager [https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/networkmanager] and Arch's VCS package guidelines for git submodules [https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git_Submodules] I've added the submodules to the source array. I doubt users will take issue with downloading directly from github via https so long as Arch's little idiosyncrasies are catered to. I suspect the majority of users won't even pay attention to where the source comes from when they start the build.

**Comment by saidinesh5** [comment]
Hi,

I propose that we do something like:

````
include(ExternalProject)
#We fetch our external dependencies at build time and compile+install them to VENDOR_DIR
set(VENDOR_DIR ${CMAKE_CURRENT_BINARY_DIR}/vendor)
set(VENDOR_INCLUDE_DIR ${VENDOR_DIR}/include)
set(VENDOR_LIB_DIR ${VENDOR_DIR}/lib)

ExternalProject_Add(
    project_jsoncpp
    GIT_REPOSITORY https://github.com/open-source-parsers/jsoncpp
    GIT_TAG master
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${VENDOR_DIR} -DCMAKE_INSTALL_LIBDIR=${VENDOR_LIB_DIR} -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF
)

include_directories(${VENDOR_INCLUDE_DIR})
link_directories(${VENDOR_LIB_DIR})

target_link_libraries(
    ${PROJECT_NAME}
    ${CMAKE_THREAD_LIBS_INIT}
    jsoncpp
)

````

This should hopefully even make our git repo lighter when dealing with commits etc.. on my ancient laptop hard drive.
Note: GIT_TAG should be something other than master in release builds..

**Comment by cwilling** [comment]
The  disadvantage of the solution using cmake is that it is activated at build time the contents of any such "extra" code modules cannot be guaranteed to be identical from one day to the next. For a repeatable build, all code to be built would ideally reside in a single tarball.

**Comment by saidinesh5** [comment]
@cwilling it should be the same as gitsubmodules. Especially if you specify the correct git revision tag.
The only "advantage" is all the dependencies go into the build directory at the time of build and make sure our repo contains only our code.
