### ISSUE TITLE
macOS installation

### ISSUE THREAD

**Issue by MarkehMe** [vovoid/vsxu#196]
Hello! 

Trying to install this on macOS but I can't seem to work it out.

Installed packages:

```
brew install glew libpng libjpeg sdl2 pulseaudio openexr
```

My cmake attempt: https://pastebin.com/CQkakfLf

CMakeOutput.log: https://pastebin.com/EM4mS4hX

**Comment by MarkehMe** [comment]
🤔 ?

**Comment by jaw** [comment]
Out of scope.
If you still want to, fork.
We don't accept pull requests for apple, maintain it on your own.

**Comment by saidinesh5** [comment]
@MarkehMe The error seems to be because no install path has been defined for Apple platforms:

https://github.com/vovoid/vsxu/blob/master/CMakeLists.txt#L25

**Comment by MarkehMe** [comment]
@jaw Out of scope? Why? 

@saidinesh5 Thanks. I've not worked with CMake before, so I'm rather unaware. I'll have a play with the CMake files.

**Comment by saidinesh5** [comment]
@MarkehMe The issue with advertising support for Apple platforms was a lot of people started asking support for it in the forums/IRC etc.. and we don't have any hardware to test / fix things out - Macs with decent graphics cards are really expensive!
The code we had related to OS X was simply left out/removed while we worked on newer features - as we had no one/no device to test out that code. (Yes, there were 2-3 ports to OS X so far, that were abandoned by the "maintainers"). That's why we encourage users to maintain their fork with the OS X patches at least until the version is good enough to merge back in.

**Comment by MarkehMe** [comment]
Okay, I'll give it a go.

**Comment by MarkehMe** [comment]
Attempting here: https://github.com/vsxu-mac/

See how I go. I will probably fail because it seems like a lot to get my head around, and I've never worked with CMake. Eeek.

**Comment by saidinesh5** [comment]
Hi, had a quick look at your repo.
A few quick observations:
cmake variable UNIX also includes OS X. So no need for if (APPLE or UNIX). Just if (UNIX) should be good enough.
Do check with homebrew guys about the install conventions/paths. Also CPack is to be used to create .dmg files. So do fix up that bit.
I think the default compiler on OSX is clang.

**Comment by MarkehMe** [comment]
Thanks so much! 

So brew installs these packages for us in `/usr/local/bin`
```
$ ls | grep gcc
gcc-7
gcc-ar-7
gcc-nm-7
gcc-ranlib-7
```

So I found myself using the gcc 7 provided by brew, you have to tell make to use it:

```
$ gcc-7 --version
gcc-7 (Homebrew GCC 7.2.0) 7.2.0

$ make CC=gcc-7
```

Just from reading it seems `clang` is a bad way to go. So we can use that one. 

I do get stopped at

```
make[2]: *** No rule to make target `lib/engine/libvsx_engine.dylib', needed by `lib/engine_graphics/libvsx_engine_graphics.dylib'.  Stop.
make[1]: *** [lib/engine_graphics/CMakeFiles/vsx_engine_graphics.dir/all] Error 2
```

So looks like I need to start with preparing myself some build targets.

**Comment by saidinesh5** [comment]
@MarkehMe check your cmake/build logs. something was missing for building libvsx_engine ...
