### ISSUE TITLE
Linux build broken by Joystick 52e47d0d76f

### ISSUE THREAD

**Issue by alown** [vovoid/vsxu#199]
Hi,

Attempting to build aea3f38779bb8c8d85b6996c834241a3a6bfdd7a on linux x86_64-pc-linux-gnu (gcc 7.3.0), ran into a variety of problems, such as missing declarations of vsx_avector in module_system_joystick.h

Reverting 52e47d0d76fa44dd9b499f5f5a1050dbb3668afc seemed to resolve all build problems - not sure if one of the libraries is out of sync with the rest of the tree here?

Thanks,

**Comment by jaw** [comment]
This most likely fixed with the latest commit in master. I managed to compile it on Ubuntu 18.04. (Albeit in Windows subsystem for Linux).
Sorry about late response, I'm not developing a /lot/ on VSXu right now :)
