### ISSUE TITLE
Documentation for player command line arguments

### ISSUE THREAD

**Issue by rmenessec** [vovoid/vsxu#201]
Is there any documentation for the player's command line arguments? If not, would you mind providing some? I'd like to be able to invoke the player directly without needing the launcher, but I can't find any documentation on what options the player takes.

**Comment by waweic** [comment]
For now, all documentation sits in the player itself and can be seen by calling it with the --help option. Hopefully, I will have time to write some documentation in the near future

**Comment by DJPlaya** [comment]
Since 05404800 (0.6.3), it is possible to select the Audio Input in the Launcher or using -audio_input_device ID

This Issue should be closed then
