### ISSUE TITLE
Linux build of v 0.6.2 fails when applied as directed.

### ISSUE THREAD

**Issue by thanatokephaloides** [vovoid/vsxu#204]
I need the full build of vsxu as I'm trying to build VLC 4.0.0. This requires the libvsxu libraries, and my distro (Ubuntu Studio 18.04) doesn't offer them.

Following your posted instructions to the letter (or as close as my distro will permit), I get the following error when CMake is run:

=================================================================================

CMake Error at lib/widget/CMakeLists.txt:90 (add_library):
  Cannot find source file:

    src/vsx_widget_window.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: vsx_widget
CMake Error: Cannot determine link language for target "vsx_widget".

=================================================================================

Any ideas as to what I'm doing wrong?

Any assistance would be most welcome. Thank You!

**Comment by jaw** [comment]
Are you building master instead of the tag?
